name: Deploy to Back4App
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: back4app Deploy Action
      uses: heinrichcoetzee/back4app-deploy-action@v4
      with:
        project: 'pev-info'
        accountKey: ${{ secrets.B4A_ACCOUNT_KEY }}